### PR TITLE
Test::Smoke::Smoker Avoid uninitialized value warning.

### PR DESCRIPTION
**Pull request by jkeenan**

### CODE REVIEW

**Comment by abeltje** [comment]
What's the use case or how do I create a testcase for this?

**Comment by jkeenan** [comment]
On 12/03/2016 10:04 AM, Abe Timmerman wrote:
> What's the use case or how do I create a testcase for this?
>

The code being modified is found within 
Test::Smoke::Smoker::make_test().  That method is only exercised in 
xt/40-smoker_ok.t.  I found that you have to say something like:
```sh
$ perl Makefile.PL && make
$ export SMOKE_VERBOSE=2 && prove -vb xt/40-smoker_ok.t
```
... in order to avoid having warnings sent to /dev/null and to thereby 
get a simulation of the LOG environment in which I encountered this warning.

If you then modify xt/40-smoker_ok.t, first in master and then in 
branch, as follows:
```diff
diff --git a/xt/40-smoker_ok.t b/xt/40-smoker_ok.t
index 76b04d4..194c7b5 100755
--- a/xt/40-smoker_ok.t
+++ b/xt/40-smoker_ok.t
@@ -44,6 +44,7 @@ use_ok( 'Test::Smoke::Smoker' );
          cfg  => $config,
          %w32args,
      } );
+    undef $smoker->{locale};

      isa_ok( $smoker, 'Test::Smoke::Smoker' );
      $smoker->mark_in;
```
... you will observe that in master you get the uninit value warning and 
in branch you do not.  I suppose you could then use $SIG{__WARN__} or 
Capture::Tiny or similar to demonstrate the absence of a warning.

Let me know if that works for you.  Thanks for looking into this.

Jim Keenan

**Comment by abeltje** [comment]
Hi Jim,
I know it took too much time to look at your comment, but relooking at what you're saying, I now know I will need more time to wrap my brain around this...

Sorry, but a decent answer will follow...

Thanks for your interest in Test::Smoke!

Good luck,

The Test::Smoke team.

**Comment by abeltje** [comment]
I have tackled this issue in a different way, it's hidden in https://github.com/abeltje/Test-Smoke/commit/eb383a13a56ce0c84165d96720e58cea1005e496

**Pull request closed without merging**
